In [1]:
import pandas as pd
from IPython.display import display

In [2]:
# This is for reading in the short form of the inverse problem
filename = 'log_short_Re{1,20,40,60,80,100}_nxnt{24,36,48,60,72}.txt'
data_master = pd.read_csv(filename, sep=" ")
# Filter out the 25,50,100
display(data_master.columns.values)

array(['tFinal', 'Re', 'nx', 'nSteps', 'alphaErr2', 'alphaErrInf', 'uErr2',
       'uErrInf', 'InverseTime', 'ErrorCheckRunTime', 'VTKRunTime', 'Total'], dtype=object)

In [3]:
display(data_master)

,tFinal,Re,nx,nSteps,alphaErr2,alphaErrInf,uErr2,uErrInf,InverseTime,ErrorCheckRunTime,VTKRunTime,Total
0,1,1,24,24,0.001280,0.000368,0.003718,0.001072,4.64900,3.00047,12.6254,20.2878
1,1,1,36,36,0.000399,0.000093,0.001386,0.000326,14.79860,9.28893,42.4244,66.5304
2,1,1,48,48,0.000176,0.000036,0.000682,0.000139,37.78020,18.28950,78.7181,134.8110
3,1,1,60,60,0.000095,0.000017,0.000392,0.000071,73.88010,30.94820,148.9090,253.7690
4,1,1,72,72,0.000057,0.000009,0.000249,0.000041,127.04600,49.61860,255.9420,432.6480
5,1,20,24,24,0.000688,0.000199,0.003602,0.001038,5.36541,3.20406,13.4790,22.0624
6,1,20,36,36,0.000198,0.000048,0.001356,0.000319,14.13150,7.63054,39.4573,61.2370
7,1,20,48,48,0.000092,0.000020,0.000671,0.000136,38.57480,16.10250,80.6796,135.3820
8,1,20,60,60,0.000056,0.000011,0.000388,0.000070,74.97480,29.25580,151.3460,255.6070
9,1,20,72,72,0.000040,0.000007,0.000248,0.000041,125.16300,49.54120,258.1300,432.8760
10,1,40,24,24,0.000546,0.000163,0.003579,0.001030,5.38910,3.11058,15.0076,23.5205
11,1,40,36,36,0.000195,0.000050,0.001359,0.000318,15.56130,7.45787,36.7341,59.7705
12,1,40,48,48,0.000110,0.000024,0.000677,0.000136,40.34680,16.24610,78.6466,135.2640
13,1,40,60,60,0.000075,0.000014,0.000394,0.000070,76.69090,29.56330,149.8900,256.1950
14,1,40,72,72,0.000056,0.000010,0.000253,0.000041,128.03600,50.09890,255.6240,433.8030
15,1,60,24,24,0.000475,0.000147,0.003567,0.001025,5.44614,3.18735,13.6042,22.2510
16,1,60,36,36,0.000205,0.000051,0.001365,0.000319,16.20840,8.11933,36.5795,60.9251
17,1,60,48,48,0.000125,0.000026,0.000683,0.000137,40.13430,17.26750,80.2986,137.7230
18,1,60,60,60,0.000087,0.000016,0.000399,0.000071,73.82700,30.11320,150.5150,254.4880
19,1,60,72,72,0.000066,0.000011,0.000258,0.000041,128.36500,49.65320,251.1160,429.1780
20,1,80,24,24,0.000455,0.000137,0.003566,0.001022,6.09756,3.35009,13.2716,22.7331
21,1,80,36,36,0.000218,0.000052,0.001373,0.000319,17.43660,7.89298,36.8371,62.1848
22,1,80,48,48,0.000136,0.000027,0.000690,0.000138,38.97770,17.26270,81.6946,137.9580
23,1,80,60,60,0.000096,0.000017,0.000405,0.000072,73.75160,30.36460,150.1460,254.2930
24,1,80,72,72,0.000072,0.000012,0.000263,0.000042,128.86000,49.71980,254.7610,433.3810
25,1,100,24,24,0.000466,0.000133,0.003574,0.001022,5.67030,3.07195,13.6275,22.3839
26,1,100,36,36,0.000230,0.000055,0.001381,0.000320,17.21830,8.22556,37.8067,63.2693
27,1,100,48,48,0.000144,0.000030,0.000696,0.000138,40.50920,15.53710,78.3109,134.3800
28,1,100,60,60,0.000101,0.000019,0.000410,0.000072,73.23380,31.19430,151.2160,255.6740
29,1,100,72,72,0.000076,0.000013,0.000267,0.000042,128.02100,49.17210,254.3640,431.6010

In [5]:
import pandas as pd
def analyze_results(log_file,output_file):
    # Get the data from the formatted csv
    data = pd.read_csv(log_file, sep=' ')
    display(data.columns.values)
    # Create the ExcelWriter to send the information to xlsx
    writer = pd.ExcelWriter(output_file)
    
    # Loop over the choices for ending time (tFinal)
    for time in data.tFinal.unique():
        # Loop over the choices for the Reynolds number (Re)
        for Re in data.Re.unique():
            # Get the information for a single pair of time and Re
            df = data[data.tFinal.eq(time) & data.Re.eq(Re)].reset_index(drop=True)
            # Get the reduction in error from the increase  in spatial/temporal resolution
            df['alphaReduction'] = df['alphaErr2'].shift(1)/df['alphaErr2']
            df['uReduction'] = df['uErr2'].shift(1)/df['uErr2']
            # Write results to a sheet in output_file
            sheetname = 'tFinal='+str(time)+', Re='+str(Re)
            df.to_excel(writer,
                       sheet_name=sheetname,
                       index=False,
                       columns=['Re','nx','nSteps',
                                    'uErr2','uReduction',
                                   'alphaErr2','alphaReduction',
                                   'InverseTime','ErrorCheckRunTime','VTKRunTime','Total'])
            sheet = writer.sheets[sheetname]
            sheet.set_column('A:I',15)
            display(df)
    
    writer.save()
    writer.close()

In [6]:
# This go was for Re={10,100}, nx=24,36,48,60,72, tFinal=1,4
log_file = 'log_short_Re{1,20,40,60,80,100}_nxnt{24,36,48,60,72}.txt'
output = 'compiled_InvProb_sensor_compare.xlsx'
analyze_results(log_file=log_file,output_file=output)

array(['tFinal', 'Re', 'nx', 'nSteps', 'alphaErr2', 'alphaErrInf', 'uErr2',
       'uErrInf', 'InverseTime', 'ErrorCheckRunTime', 'VTKRunTime', 'Total'], dtype=object)

,tFinal,Re,nx,nSteps,alphaErr2,alphaErrInf,uErr2,uErrInf,InverseTime,ErrorCheckRunTime,VTKRunTime,Total,alphaReduction,uReduction
0,1,1,24,24,0.001280,0.000368,0.003718,0.001072,4.6490,3.00047,12.6254,20.2878,NaN,NaN
1,1,1,36,36,0.000399,0.000093,0.001386,0.000326,14.7986,9.28893,42.4244,66.5304,3.207125,2.682699
2,1,1,48,48,0.000176,0.000036,0.000682,0.000139,37.7802,18.28950,78.7181,134.8110,2.261911,2.033121
3,1,1,60,60,0.000095,0.000017,0.000392,0.000071,73.8801,30.94820,148.9090,253.7690,1.866073,1.739293
4,1,1,72,72,0.000057,0.000009,0.000249,0.000041,127.0460,49.61860,255.9420,432.6480,1.653958,1.573814

,tFinal,Re,nx,nSteps,alphaErr2,alphaErrInf,uErr2,uErrInf,InverseTime,ErrorCheckRunTime,VTKRunTime,Total,alphaReduction,uReduction
0,1,20,24,24,0.000688,0.000199,0.003602,0.001038,5.36541,3.20406,13.4790,22.0624,NaN,NaN
1,1,20,36,36,0.000198,0.000048,0.001356,0.000319,14.13150,7.63054,39.4573,61.2370,3.479422,2.657037
2,1,20,48,48,0.000092,0.000020,0.000671,0.000136,38.57480,16.10250,80.6796,135.3820,2.142885,2.020753
3,1,20,60,60,0.000056,0.000011,0.000388,0.000070,74.97480,29.25580,151.3460,255.6070,1.637484,1.729902
4,1,20,72,72,0.000040,0.000007,0.000248,0.000041,125.16300,49.54120,258.1300,432.8760,1.417630,1.565141

,tFinal,Re,nx,nSteps,alphaErr2,alphaErrInf,uErr2,uErrInf,InverseTime,ErrorCheckRunTime,VTKRunTime,Total,alphaReduction,uReduction
0,1,40,24,24,0.000546,0.000163,0.003579,0.001030,5.3891,3.11058,15.0076,23.5205,NaN,NaN
1,1,40,36,36,0.000195,0.000050,0.001359,0.000318,15.5613,7.45787,36.7341,59.7705,2.796333,2.632946
2,1,40,48,48,0.000110,0.000024,0.000677,0.000136,40.3468,16.24610,78.6466,135.2640,1.771213,2.008629
3,1,40,60,60,0.000075,0.000014,0.000394,0.000070,76.6909,29.56330,149.8900,256.1950,1.470124,1.719421
4,1,40,72,72,0.000056,0.000010,0.000253,0.000041,128.0360,50.09890,255.6240,433.8030,1.343198,1.554666

,tFinal,Re,nx,nSteps,alphaErr2,alphaErrInf,uErr2,uErrInf,InverseTime,ErrorCheckRunTime,VTKRunTime,Total,alphaReduction,uReduction
0,1,60,24,24,0.000475,0.000147,0.003567,0.001025,5.44614,3.18735,13.6042,22.2510,NaN,NaN
1,1,60,36,36,0.000205,0.000051,0.001365,0.000319,16.20840,8.11933,36.5795,60.9251,2.311387,2.612571
2,1,60,48,48,0.000125,0.000026,0.000683,0.000137,40.13430,17.26750,80.2986,137.7230,1.639521,1.998326
3,1,60,60,60,0.000087,0.000016,0.000399,0.000071,73.82700,30.11320,150.5150,254.4880,1.431148,1.710379
4,1,60,72,72,0.000066,0.000011,0.000258,0.000041,128.36500,49.65320,251.1160,429.1780,1.329825,1.545659

,tFinal,Re,nx,nSteps,alphaErr2,alphaErrInf,uErr2,uErrInf,InverseTime,ErrorCheckRunTime,VTKRunTime,Total,alphaReduction,uReduction
0,1,80,24,24,0.000455,0.000137,0.003566,0.001022,6.09756,3.35009,13.2716,22.7331,NaN,NaN
1,1,80,36,36,0.000218,0.000052,0.001373,0.000319,17.43660,7.89298,36.8371,62.1848,2.088953,2.597637
2,1,80,48,48,0.000136,0.000027,0.000690,0.000138,38.97770,17.26270,81.6946,137.9580,1.600640,1.990323
3,1,80,60,60,0.000096,0.000017,0.000405,0.000072,73.75160,30.36460,150.1460,254.2930,1.422212,1.703189
4,1,80,72,72,0.000072,0.000012,0.000263,0.000042,128.86000,49.71980,254.7610,433.3810,1.327526,1.538477

,tFinal,Re,nx,nSteps,alphaErr2,alphaErrInf,uErr2,uErrInf,InverseTime,ErrorCheckRunTime,VTKRunTime,Total,alphaReduction,uReduction
0,1,100,24,24,0.000466,0.000133,0.003574,0.001022,5.6703,3.07195,13.6275,22.3839,NaN,NaN
1,1,100,36,36,0.000230,0.000055,0.001381,0.000320,17.2183,8.22556,37.8067,63.2693,2.025432,2.587975
2,1,100,48,48,0.000144,0.000030,0.000696,0.000138,40.5092,15.53710,78.3109,134.3800,1.596954,1.984422
3,1,100,60,60,0.000101,0.000019,0.000410,0.000072,73.2338,31.19430,151.2160,255.6740,1.422771,1.697597
4,1,100,72,72,0.000076,0.000013,0.000267,0.000042,128.0210,49.17210,254.3640,431.6010,1.328298,1.532789